cargo-features = ["codegen-backend"]
[workspace]
members = [
  "constraint_schema",
  "molecule_schema",
  "generate_schema",
  "serde_types",
  "output_types",
]

[profile.dev]
debug = 0
codegen-backend = "cranelift"
