# cargo-features = ["codegen-backend"]
[workspace]
resolver = "2"
members = [
  "molecule_schema",
  "generate_schema_reactive",
  "base_types",
  "reactive_types",
]


# [profile.dev]
# debug = 0
# codegen-backend = "cranelift"
