# cargo-features = ["codegen-backend"]
[workspace]
resolver = "2"
members = [
    "molecule_schema",
    "generate_schema_reactive",
    "base_types",
    "reactive_types",
    "to_composite_id_macro",
    "molecule_core",
]


# [profile.dev]
# debug = 0
# codegen-backend = "cranelift"
