
[package]
name = "to_composite_id_macro"
version = "0.1.0"
edition = "2021"

[dependencies]
typenum = "1"
syn = { version = "2.0", features = ["full"] }
quote = "1.0"
proc-macro2 = "1"
molecule_core = { path = "../molecule_core" }

[lib]
proc-macro = true
