[package]
name = "generate_schema_macro"
version = "0.1.0"
edition = "2021"

[lib]
proc-macro = true

[dependencies]
molecule_schema = { path = "../molecule_schema" }
molecule_types = { path = "../molecule_types" }
syn = { version = "2.0", features = ["full"] }
quote = "1.0"
proc-macro2 = "1"
